# Multiple Linear Regression

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

data={
    'InternalMarks':[15,23,18,23,24],
    'ExternalMarks':[49,63,58,60,61],
    'Marks':[10,20,30,40,50]
}
df=pd.DataFrame(data)

In [2]:
x=df[['InternalMarks','Marks']]
y=df['ExternalMarks']

In [3]:
# 206
# For the given RealEstate csv, write a python program satisfying following tasks to demonstrate application of machine learning
# through multiple linear regression as follows –
# Given: -
# Dataset RealEstate.csv
# ML Library to be used scikit-learn
# Dependent variable 'Y house price of unit area'
# Independent variables 'X1 transaction date', 'X2 house age', 'X3 distance to the nearest MRT station', 'X4 number of
# convenience stores', 'X5 latitude' and 'X6 longitude'

In [ ]:
# 1.Import required libraries.

from sklearn.linear_model import LinearRegression  
from sklearn.model_selection import train_test_split  
from sklearn.metrics import mean_squared_error
import math

In [5]:
# 2. Load RealEstate dataset, create a dataframe and check datatypes of its attributes using appropriate method.
df=pd.read_csv('RealEstate.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   No                                      414 non-null    int64
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB

In [6]:
# 3. Remove ‘No’ column from the dataframe.
df.drop('No',axis=1,inplace=True)

In [7]:
# 4. Check for any null values in features using appropriate method.
df.isna().sum()

X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [8]:
# 5. Create feature variables x and y as given above.
x=df[['X1 transaction date','X2 house age','X3 distance to the nearest MRT station','X4 number of convenience stores','X5 latitude','X6 longitude']]
y=df['Y house price of unit area']

In [9]:
# 6. Create training and testing sets of feature variables with 70% of data for training and with random state of 110.
X_train, X_test, Y_train, Y_test = train_test_split( x, y, test_size = 0.3, random_state = 110 )

In [10]:
# 7. Create and fit regression model using appropriate method.
model=LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [11]:
# 8. Use testing set created in step 6 to find and print the prediction of the outcome.
y_pred=model.predict(X_test)

In [12]:
# 9. Find and print coefficient and mean squared error of the regression model.
print(model.coef_[0])
print(mean_squared_error(Y_test,y_pred))

6.843089410816098
77.14802598253651

In [13]:
# 208
# Write a program to create a Model using linear regression to predict the wine quality using the csv file provided named
# “winequality.csv”. Do the required process in the data before making a model.
# If you find any null value in “winequality.csv” then replace null value with mean value of respected columns.
# Find co-efficient, intercept and mean squared error.
# also Predict the quality of red wine for the following data:
# fixed acidity: 8
# volatile acidity: 0.4
# citric acid: 0.40
# residual sugar: 15
# chlorides: 0.048
# free sulfur dioxide: 40
# total sulfur dioxide: 150
# density: 0.99
# pH: 3
# sulphates: 0.45
# alcohol: 10.5

In [ ]:
import pandas as pd 
from sklearn.linear_model import LinearRegression  
from sklearn.model_selection import train_test_split  
from sklearn.metrics import mean_squared_error

df=pd.read_csv('winequality.csv')
df

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
1,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
2,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6491,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6492,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6493,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6494,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6495,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [49]:
df=pd.get_dummies(df,drop_first=True)
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type_white
0,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6,True
1,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6,True
2,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,True
3,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,True
4,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6491,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,False
6492,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6,False
6493,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,False
6494,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,False
6495,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,False

In [50]:
df.isna().sum()

fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
type_white               0
dtype: int64

In [51]:
df.fillna(df.mean(numeric_only=True),inplace=True)
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
type_white              0
dtype: int64

In [52]:
x=df.drop('quality',axis=1)  # Feature
y=df['quality']  #Label

In [53]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [54]:
model=LinearRegression()
model.fit(X_train,Y_train)
y_pred=model.predict(X_test)

In [55]:
mse=mean_squared_error(Y_test,y_pred)
print(mse)
print(model.coef_[0])
print(model.intercept_)

0.5135971931947765
0.09136043623986105
112.55859569389033

In [56]:
inputData=pd.DataFrame([{'fixed acidity': 8,'volatile acidity': 0.4,'citric acid': 0.40,'residual sugar': 15,'chlorides': 0.048,'free sulfur dioxide': 40,'total sulfur dioxide': 150,'density': 0.99,'pH': 3,'sulphates': 0.45,'alcohol': 10.5,'type_white': False}])
model.predict(inputData)

array([7.07309203])